### ISSUE TITLE
Make the instructions clearer (i.e. clarifying what students need to aim for, where to start)

### ISSUE THREAD

**Issue by joeylouise** [RhodesPeter/request-module-workshop#3]
Make it clearer what is required in this (some people were sat around not knowing what to do)

e.g. give students a clue that they will be using response.on('data'), ('end') etc.

**Comment by joeylouise** [comment]
@RhodesPeter, is it ok if @majakudlicka works on this issue?

**Comment by RhodesPeter** [comment]
Hi @joeylouise - Yes please go for it :) 

When you have done the work make a PR and I will have a look over it.

**Comment by RhodesPeter** [comment]
I am closing this issue as we have fixed it with commit a516f0f 🎉
